# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Add two CharacterVectors.
#'
#' @name addTwoVectors
#' @param v1: CharacterVector
#' @param v2: CharacterVector
#' @return CharacterVector that has all the elements of the given vectors. Elements in v1 come first.
#' @examples
#' addTwoVectors(c("A", "B", "C"), c("D", "E", "F")) => c("A", "B", "C", "D", "E", "F")
#' addTwoVectors(c("D", "E", "F"), c("A", "B", "C")) => c("D", "E", "F", "A", "B", "C")
NULL

#' Add two strings alphabetically.
#'
#' @name addStrings
#' @param s1: string
#' @param s2: string
#' @return string which contains given strings
#' @examples
#' addStrings("abc", "def") => "abcdef"
#' addStrings("def", "abc") => "abcdef"
NULL

#' Collect data about patients.
#'
#' Finds drug trajectory for every patient.
#'
#' @param data: dataframe
#' @param IDs: numeric vector
#' @param n: integer, n > 0 - length of drug trajectory
#' @return list with vectors named "IDs" and "drugs". "IDs" hold information about patients IDs and "drugs" contains n-length drug trajectory per patient
#' @export
collectPatientData <- function(data, IDs, n) {
    .Call('_ClusterPatientsTrajectories_collectPatientData', PACKAGE = 'ClusterPatientsTrajectories', data, IDs, n)
}

#' Compare patients drug trajectories.
#'
#' @param patientsData: list with patient IDs and their drug trajectories
#' @param punishments: numeric vector
#' @return numeric matrix with distances between patients drug trajectories
#' @export
compareDrugTrajectories <- function(patientsData, punishments) {
    .Call('_ClusterPatientsTrajectories_compareDrugTrajectories', PACKAGE = 'ClusterPatientsTrajectories', patientsData, punishments)
}

#' Compare patients drug trajectories with DTW algorithm.
#'
#' @param patientsData: list with patient IDs and their drug trajectories
#' @param punishments: numeric vector
#' @return numeric matrix with distances between patients drug trajectories
#' @export
compareDrugTrajectoriesWithDTW <- function(patientsData, punishments) {
    .Call('_ClusterPatientsTrajectories_compareDrugTrajectoriesWithDTW', PACKAGE = 'ClusterPatientsTrajectories', patientsData, punishments)
}

#' Find the occurrences of given drugs per patient.
#'
#' @param data: dataframe
#' @param IDs: numeric vector
#' @param drugs: character vector
#' @return numeric matrix which has count of given drugs per patient
#' @export
countDrugsInCluster <- function(data, IDs, drugs) {
    .Call('_ClusterPatientsTrajectories_countDrugsInCluster', PACKAGE = 'ClusterPatientsTrajectories', data, IDs, drugs)
}

#' Normalize all non-zero values in matrix with log10.
#'
#' @param values: numeric matrix
#' @return matrix where all non-zero values have been normalized.
#' @export
normalize <- function(values) {
    .Call('_ClusterPatientsTrajectories_normalize', PACKAGE = 'ClusterPatientsTrajectories', values)
}

